channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - jupytext
  - nodejs
  - mcstas=3.5.27
  - mcxtrace=3.5.27
  - mccode-antlr
  - mcstasscript
  - rsync
  - xraylib
  - ncrystal
  - mcpl
  - nexus
  - openmpi
  - nbgitpuller
  - pip:
      - .
